project:
  output-dir: _site/download
  render:
    # - pages/03-git-github/03-github-portfolio/05-map.qmd
    # - notebooks/05-vegetation/vegetation.qmd
    # - notebooks/01-climate/climate-9*.qmd
    # - notebooks/03-species-distribution/species-distribution-9*.qmd
    - notebooks/10-redlining/redlining-9*.qmd

execute:
  output: false
  cache: false