project:
  type: website
  render:
    - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
    - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
    - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
    - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
    - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd
    - index.qmd

bibliography: site_sources.bib

filters:
  - pyodide
  - fontawesome

website:
  navbar:
    search: true
    logo: img/ESIIL_portal.png
    logo-alt: "ESIIL Learning Portal"
    logo-href: "index.html"
    right:
      - href: "http://earthdatascience.org"
        text: "Classic earthdatascience.org"
  bread-crumbs: true
  page-footer:
    border: false
    left: 
      - text: "About ESIIL"
        href: "https://esiil.org/"

sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - section: "Unit 1"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
            - section: "Text File Types"
              contents:
                - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
            - section: "Version Control"
              contents:
                - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
                - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
                - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
                - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
                
format:
  html:
    theme: [flatly, theme-esiil-light.scss]
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?!((http:|https:)\/\/))'
    template-partials:
      - partials/title-block.html
    
code-annotations: "below"



