project:
  output-dir: _site/foundations
  render:
    - pages/00-course-overviews/foundations/
    - pages/01-reproducible-science-tools/open-reproducible-science/
    - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
    - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
    - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
    - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
    - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
    - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd
    - pages/03-git-github/03-github-portfolio/
    - notebooks/01-climate/climate-3*.qmd
    - notebooks/01-climate/climate.qmd
    - notebooks/03-species-distribution/species-distribution-3*.qmd
    - notebooks/03-species-distribution/species-distribution.qmd
    - notebooks/10-redlining/redlining-3*.qmd
    - notebooks/10-redlining/redlining-4*.qmd
    - notebooks/10-redlining/redlining.qmd
    - notebooks/08-habitat/habitat.qmd
    - notebooks/11-big-data/big-data.qmd
    - notebooks/12-clustering/clustering.qmd
    - notebooks/13-habitat-climate-change/climate.qmd
    - "!index.qmd"

website:
  page-navigation: true
  comments:
    giscus: 
      repo: earthlab-education/Earth-Analytics-AY24
  navbar:
    logo-href: "/../index.html"
    left:
      - text: Earth Data Analytics -- Foundations
        href: pages/00-course-overviews/foundations/00-home.qmd
      - text: Courses
        menu:     
          - text: "COURSE 1: Fundamentals of Earth Data Analytics"
            href: pages/00-course-overviews/foundations/01-fundamentals/00-home.qmd
          - text: "COURSE 2: Topics in Earth Analytics"
            href: pages/00-course-overviews/foundations/02-topics/00-home.qmd
          - text: "COURSE 3: Earth Analytics Applications"
            href: pages/00-course-overviews/foundations/03-applications/00-home.qmd

  sidebar:
    - title: "COURSE 1: Fundamentals of Earth Data Analytics"
      style: docked
      border: false
      search: true
      contents:
        - pages/00-course-overviews/foundations/01-fundamentals/00-home.qmd
        - section: "Unit 1: Portfolio"
          href: pages/00-course-overviews/foundations/01-fundamentals/01-portfolio.qmd
          contents: 
            - section: "Text File Types"
              contents:
                - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
            - section: "Version Control"
              contents:
                - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
                - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
                - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
                - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
            - section: "Portfolio"
              contents:
                - pages/03-git-github/03-github-portfolio/00-introduction.qmd
                - pages/03-git-github/03-github-portfolio/01-create-portfolio-website.qmd
                - pages/03-git-github/03-github-portfolio/02-images.qmd
                - pages/03-git-github/03-github-portfolio/03-html.qmd
                - pages/03-git-github/03-github-portfolio/04-jekyll.qmd
                - pages/03-git-github/03-github-portfolio/05-map.qmd
                - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd
        - section: "Unit 2: Time-series Data"
          href: pages/00-course-overviews/foundations/01-fundamentals/02-time-series.qmd
          contents: 
            - section: "Open Science Tools"
              contents:
                - pages/01-reproducible-science-tools/open-reproducible-science/01-intro.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/02-open-science-tools.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/03-best-practices.qmd
            - section: "Time-series Data"
            - section: "Climate Coding Challenge"
              contents:
                - notebooks/01-climate/climate.qmd
        - section: "Unit 3: Vector Data"
          href: pages/00-course-overviews/foundations/01-fundamentals/03-vector.qmd
          contents: 
            - section: "Geospatial Vector Data"
            - section: "Species Distribution Coding Challenge"
              contents:
                - notebooks/03-species-distribution/species-distribution.qmd
        - section: "Unit 4: Raster Data"
          href: pages/00-course-overviews/foundations/01-fundamentals/04-raster.qmd
          contents: 
            - text: "Install Python on your computer"
              href: https://www.earthdatascience.org/workshops/setup-earth-analytics-python/setup-git-bash-conda/
            - section: "Geospatial Raster Data"
            - section: "Urban Greenspace and Redlining Coding Challenge"
              contents:
                - notebooks/10-redlining/redlining.qmd
        - section: "Final: Habitat Suitability"
          href: pages/00-course-overviews/foundations/01-fundamentals/05-final.qmd
          contents: 
            - section: "Climate Data 101"
            - section: "Habitat Suitability Coding Challenge"
              contents:
                - notebooks/08-habitat/habitat.qmd
    - title: "COURSE 2: Topics in Earth Analytics"
      contents:
        - pages/00-course-overviews/foundations/02-topics/00-home.qmd
        - section: "Unit 1: Big Data"
          href: pages/00-course-overviews/foundations/02-topics/01-big-data.qmd
          contents: 
            - notebooks/11-big-data/big-data.qmd
        - section: "Unit 2: Clustering"
          href: pages/00-course-overviews/foundations/02-topics/02-clustering.qmd
          contents: 
            - notebooks/12-clustering/clustering.qmd
        - section: "Unit 3: Climate Model Data"
          href: pages/00-course-overviews/foundations/02-topics/02-clustering.qmd
          contents: 
            - notebooks/13-habitat-climate-change/climate.qmd

params:
  01-climate:
    location: "Boulder, CO"
    station_id: "USC00050848"
    start_date: "1893-10-01"
    end_date: "2023-09-30"
    output_filename: "climate-foundations-data.csv"