project:
  output-dir: _site/mefa
  render:
    - notebooks/07-phenocam/*.qmd
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: MEFA Phenocam Workshop
        href: pages/00-course-overviews/mefa/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - pages/00-course-overviews/mefa/00-home.qmd
        - notebooks/07-phenocam/phenocam.qmd
        - text: Try it on GitHub!
          href: https://classroom.github.com/a/-Z4A07Cz