project:
  output-dir: _site/shortcourse
  render:
    - pages/00-course-overviews/shortcourse/00-home.qmd
    - pages/00-course-overviews/shortcourse/01-collaboration/
    - pages/00-course-overviews/shortcourse/02-data/
    - pages/00-course-overviews/shortcourse/03-reproducible/
    - pages/00-course-overviews/shortcourse/04-cyberinfrastructure/
    - pages/01-reproducible-science-tools/open-reproducible-science/
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: ESIIL Data Short Course Home
        href: pages/00-course-overviews/shortcourse/00-home.qmd
      - text: Courses
        menu:     
          - text: "COURSE 1: Cloud Computing, Collaboration, and Communication"
            href: pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
          - text: "COURSE 2: Ethical Earth Data Use"
            href: pages/00-course-overviews/shortcourse/02-data/00-home.qmd
          - text: "COURSE 3: Readable, Modular, Reproducible Code"
            href: pages/00-course-overviews/shortcourse/03-reproducible/00-home.qmd
          - text: "COURSE 4: Cyberinfrastructure"
            href: pages/00-course-overviews/shortcourse/04-cyberinfrastructure/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
        - section: "Unit 1"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/01-join-our-community.qmd
        - section: "Unit 2"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/02-open-science.qmd
            - section: "Open Science Tools"
              contents:
                - pages/01-reproducible-science-tools/open-reproducible-science/01-intro.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/02-open-science-tools.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/03-best-practices.qmd
        - section: "Unit 3"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/03-geospatial.qmd
        - section: "Unit 4"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/04-applications.qmd
    
    - title: "Ethical Earth Data Use"
      contents: 
        - pages/00-course-overviews/shortcourse/02-data/00-home.qmd

    - title: "Reproducible Science"
      contents: 
        - pages/00-course-overviews/shortcourse/03-reproducible/00-home.qmd

    - title: "Cyberinfrastructure"
      contents: 
        - pages/00-course-overviews/shortcourse/04-cyberinfrastructure/00-home.qmd

    - title: "ESIIL Data Short Course"
      contents:
          - pages/00-course-overviews/shortcourse/00-home.qmd
          - section: Courses
            contents:
              - pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
              - pages/00-course-overviews/shortcourse/02-data/00-home.qmd
              - pages/00-course-overviews/shortcourse/03-reproducible/00-home.qmd
              - pages/00-course-overviews/shortcourse/04-cyberinfrastructure/00-home.qmd