project:
  output-dir: _site/shortcourse
  render:
    - pages/00-course-overviews/shortcourse/00-home.qmd
    - pages/00-course-overviews/shortcourse/01-collaboration/
    - pages/00-course-overviews/shortcourse/02-data/
    - pages/00-course-overviews/shortcourse/03-reproducible/
    - pages/00-course-overviews/shortcourse/04-cyberinfrastructure/
    - pages/01-reproducible-science-tools/open-reproducible-science/
    - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
    - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
    - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
    - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
    - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
    - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd
    - pages/03-git-github/03-github-portfolio/
    - notebooks/01b-get-started-api/get-started-api.qmd
    - notebooks/05-vegetation/vegetation.qmd
    - "!index.qmd"

website:
  page-navigation: true
  comments:
    giscus: 
      repo: cu-esiil-edu/2024-data-short-course
  navbar:
    logo-href: "/../index.html"
    left:
      - text: ESIIL Data Short Course Home
        href: pages/00-course-overviews/shortcourse/00-home.qmd
      - text: Courses
        menu:     
          - text: "COURSE 1: Cloud Computing, Collaboration, and Communication"
            href: pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
          - text: "COURSE 2: Ethical Earth Data Use"
            href: pages/00-course-overviews/shortcourse/02-data/00-home.qmd
          - text: "COURSE 3: Readable, Modular, Reproducible Code"
            href: pages/00-course-overviews/shortcourse/03-reproducible/00-home.qmd
          - text: "COURSE 4: Cyberinfrastructure"
            href: pages/00-course-overviews/shortcourse/04-cyberinfrastructure/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - section: "Unit 1"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
            - section: "Text File Types"
              contents:
                - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
            - section: "Version Control"
              contents:
                - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
                - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
                - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
                - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
            - section: "Portfolio"
              contents:
                - pages/03-git-github/03-github-portfolio/00-introduction.qmd
                - pages/03-git-github/03-github-portfolio/01-create-portfolio-website.qmd
                - pages/03-git-github/03-github-portfolio/02-images.qmd
                - pages/03-git-github/03-github-portfolio/03-html.qmd
                - pages/03-git-github/03-github-portfolio/04-jekyll.qmd
                - pages/03-git-github/03-github-portfolio/05-map.qmd
                - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd
        - section: "Unit 2"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/02-open-science.qmd
            - section: "Open Science Tools"
              contents:
                - pages/01-reproducible-science-tools/open-reproducible-science/01-intro.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/02-open-science-tools.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/03-best-practices.qmd
            - section: "Climate Coding Challenge"
              contents:
                - notebooks/01b-get-started-api/get-started-api.qmd
        - section: "Unit 3"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/03-geospatial.qmd
            - section: "Geospatial Data"
            - section: "Vegetation Coding Challenge"
              contents:
                - notebooks/05-vegetation/vegetation.html
        - section: "Unit 4"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/04-applications.qmd
    
    - title: "Ethical Earth Data Use"
      contents: 
        - pages/00-course-overviews/shortcourse/02-data/00-home.qmd

    - title: "Reproducible Science"
      contents: 
        - pages/00-course-overviews/shortcourse/03-reproducible/00-home.qmd

    - title: "Cyberinfrastructure"
      contents: 
        - pages/00-course-overviews/shortcourse/04-cyberinfrastructure/00-home.qmd

    - title: "ESIIL Data Short Course"
      contents:
          - pages/00-course-overviews/shortcourse/00-home.qmd
          - section: Courses
            contents:
              - pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
              - pages/00-course-overviews/shortcourse/02-data/00-home.qmd
              - pages/00-course-overviews/shortcourse/03-reproducible/00-home.qmd
              - pages/00-course-overviews/shortcourse/04-cyberinfrastructure/00-home.qmd