project:
  output-dir: _notebooks
  render:
    # - pages/03-git-github/03-github-portfolio/05-map.qmd
    # - notebooks/05-vegetation/vegetation.qmd
    - notebooks/01-climate/climate-3*-*.qmd

execute:
  output: false
  cache: true

format: 
  ipynb: default