project:
  type: website
  pre-render:
    - scripts/insert_code_params.py
  render:
    - index.qmd
  post-render:
    - scripts/restore_original_files.py

bibliography: site_sources.bib

filters:
  - pyodide
  - fontawesome

website:
  navbar:
    search: true
    logo: img/ESIIL_portal.png
    logo-alt: "ESIIL Learning Portal"
    logo-href: "index.html"
    right:
      - href: "http://earthdatascience.org"
        text: "Classic earthdatascience.org"
  bread-crumbs: true
  page-footer:
    border: false
    left: 
      - text: "About ESIIL"
        href: "https://esiil.org/"
        
format:
  html:
    theme: [flatly, theme-esiil-light.scss]
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?!((http:|https:)\/\/))'
    template-partials:
      - partials/title-block.html
    
code-annotations: "below"
