project:
  output-dir: _notebooks
  render:
    - pages/03-git-github/03-github-portfolio/05-map.qmd
    - notebooks/05-vegetation/vegetation.qmd

execute:
  output: false
  cache: true

filters: 
  - fontawesome

format: 
  ipynb: default
  html:
    output-ext: 'html'