project:
  output-dir: _site/stars
  render:
    - pages/00-course-overviews/stars/00-home.qmd
    - pages/00-course-overviews/stars/*/*.qmd
    - pages/01-reproducible-science-tools/open-reproducible-science/
    - pages/03-git-github/03-github-portfolio/
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: ESIIL Stars Home
        href: pages/00-course-overviews/stars/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true
      logo: images/ESIIL_Stars_logo.png
      collapse-level: 1

      contents:
        - section: "UNIT 1: Build Your Online Portfolio"
          contents: 
            - pages/00-course-overviews/stars/01-portfolio/00-home.qmd
            - pages/03-git-github/03-github-portfolio/00-introduction.qmd
            - pages/03-git-github/03-github-portfolio/01-create-portfolio-website.qmd
        - section: "UNIT 2: Climate Change"
          contents: 
            - pages/00-course-overviews/stars/02-climate-change/00-home.qmd
        - section: "UNIT 3: Flooding"
          contents: 
            - pages/00-course-overviews/stars/03-flooding/00-home.qmd
        - section: "UNIT 4: Species Distribution"
          contents: 
            - pages/00-course-overviews/stars/04-species-distribution/00-home.qmd
        - section: "UNIT 5: Air Quality"
          contents: 
            - pages/00-course-overviews/stars/05-air-quality/00-home.qmd