project:
  output-dir: _site/css
  render:
    - pages/00-course-overviews/css/00-home.qmd
    - pages/01-reproducible-science-tools/open-reproducible-science/01-intro.qmd
    - notebooks/09-urban-heat-island/uhi-3*.qmd
    - notebooks/09-urban-heat-island/urban-heat-island.qmd
    - notebooks/01-climate/climate-98-download.qmd
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: Indigenous Data Science Workshop with Chicago Symposium
        href: pages/00-course-overviews/css/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - text: Workshop Overview
          href: pages/00-course-overviews/css/00-home.qmd
        - text: Chicago Symposium
          href: https://chicagosymposium.org/
        - text: ESIIL
          href: https://esiil.org/
        - text: Plenary Speakers
          href: https://chicagosymposium.org/profile/139/
        - section: Session 1
          contents:
            - text: Open Reproducible Science
              href: pages/01-reproducible-science-tools/open-reproducible-science/01-intro.qmd
            - text: Urban Heat Island
              href: notebooks/09-urban-heat-island/urban-heat-island.qmd
            - text: Data Download
              href: notebooks/01-climate/climate-98-download.qmd
            - text: Try it on GitHub!
              href: https://classroom.github.com/a/D24VgT6A

params:
  01-climate:
    location: "Chicago, IL"
    station_id: "USW00094846"
    start_date: "1950-10-01"
    end_date: "2023-09-30"
    output_filename: "climate-chicago-data.csv"