project:
  output-dir: _notebooks
  post-render:
    - scripts/restore_original_files.py
  render:
    # - pages/03-git-github/03-github-portfolio/05-map.qmd
    # - notebooks/05-vegetation/vegetation.qmd
    # - notebooks/01-climate/climate-*.qmd
    # - notebooks/09-urban-heat-island/uhi-*.qmd
    # - notebooks/03-species-distribution/species-distribution-*.qmd
    - notebooks/10-redlining/redlining-4*.qmd

execute:
  eval: false
  output: false

format: 
  ipynb: default