project:
  output-dir: _site/css
  render:
    - pages/00-overviews/events/css/index.qmd
    - pages/00-overviews/events/css/*/index.qmd
    - pages/01-reproducible-science-tools/open-reproducible-science/01-overview.qmd
    - notebooks/09-urban-heat-island/uhi-3*.qmd
    - notebooks/09-urban-heat-island/urban-heat-island.qmd
    - notebooks/01-climate/climate-98-download.qmd
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: Indigenous Data Science Workshop with Chicago Symposium
        href: pages/00-overviews/events/css/index.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - text: Workshop Overview
          href: pages/00-overviews/events/css/index.qmd
          contents:
            - text: Chicago Symposium
              href: https://chicagosymposium.org/
            - text: ESIIL
              href: https://esiil.org/
            - text: Plenary Speakers
              href: https://chicagosymposium.org/profile/139/
        - section: Session 1 -- Chicago Heat Wave
          href: pages/00-overviews/events/css/01-urban-heat/index.qmd
          contents:
            - text: Make a Free GitHub Account
              href: https://github.com/signup
            - text: Open, Reproducible Science
              href: pages/01-reproducible-science-tools/open-reproducible-science/01-overview.qmd
            - text: Urban Heat Island
              href: notebooks/09-urban-heat-island/urban-heat-island.qmd
            - text: Data Download
              href: notebooks/01-climate/climate-98-download.qmd
            - text: Try it on GitHub!
              href: https://classroom.github.com/a/D24VgT6A
        - text: Session 2 -- Facilitating cross-cultural projects
          href: pages/00-overviews/events/css/02-facilitating/index.qmd
        - text: Session 3 -- You don't need to be an expert to teach coding
          href: pages/00-overviews/events/css/03-ai-peer/index.qmd
        - section: More ESIIL?
          contents:
            - text: "Join our mailing list."
              href: https://esiil.org/contact-0
            - text: Article - Fostering the Development of Earth Data Science Skills in a Diverse Community of Online Learners
              href: https://www.tandfonline.com/doi/full/10.1080/26939169.2024.2362886
            - text: Article - The fastest-growing and most destructive fires in the US
              href: https://www.science.org/doi/10.1126/science.adk5737

params:
  01-climate:
    location: "Chicago, IL"
    station_id: "USW00094846"
    start_date: "1950-10-01"
    end_date: "2023-09-30"
    output_filename: "climate-chicago-data.csv"