project:
  output-dir: _site/shortcourse
  render:
    - pages/00-course-overviews/hyrsense/00-home.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
    - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
    - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
    - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
    - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
    - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
    - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd
    - pages/03-git-github/03-github-portfolio/
    - "!index.qmd"

website:
  page-navigation: true
  comments:
    giscus: 
      repo: cu-esiil-edu/HYR-SENSE
  navbar:
    logo-href: "/../index.html"
    left:
      - text: HYR-SENSE Home
        href: pages/00-course-overviews/hyrsense/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - section: "Playing with GitHub"
          contents: 
            - pages/00-course-overviews/shortcourse/01-collaboration/00-home.qmd
            - section: "Text File Types"
              contents:
                - pages/02-file-formats-eds/04-text-file-formats-eds/01-intro-text-file-formats.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/02-markdown.qmd
                - pages/02-file-formats-eds/04-text-file-formats-eds/03-tabular-data.qmd
            - section: "Version Control"
              contents:
                - pages/03-git-github/01-intro-version-control/01-intro-version-control.qmd
                - pages/03-git-github/02-github-collaboration/01-intro-collaboration.qmd
                - pages/03-git-github/02-github-collaboration/02-pull-requests.qmd
                - pages/03-git-github/02-github-collaboration/06-pr-activity-fork.qmd
            - section: "Portfolio"
              contents:
                - pages/03-git-github/03-github-portfolio/00-introduction.qmd
                - pages/03-git-github/03-github-portfolio/01-create-portfolio-website.qmd
                - pages/03-git-github/03-github-portfolio/02-images.qmd
                - pages/03-git-github/03-github-portfolio/03-html.qmd
                - pages/03-git-github/03-github-portfolio/04-jekyll.qmd
                - pages/03-git-github/03-github-portfolio/05-map.qmd
                - pages/03-git-github/02-github-collaboration/07-pr-activity-branch.qmd