project:
  output-dir: _site/stars
  render:
    - pages/00-course-overviews/stars/00-home.qmd
    - pages/00-course-overviews/stars/01-portfolio/
    - pages/01-reproducible-science-tools/open-reproducible-science/
    - pages/03-git-github/03-github-portfolio/
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: ESIIL Stars Home
        href: pages/00-course-overviews/stars/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true
      logo: img/ESIIL_Stars_logo.png
      collapse-level: 1

      contents:
        - section: "UNIT 1: Build Your Online Portfolio"
          contents:
            - pages/03-git-github/03-github-portfolio/00-introduction.qmd
            - text: "STEP 1: Publish a website"
              href: pages/03-git-github/03-github-portfolio/01-create-portfolio-website.qmd
            - text: "STEP 2: Add images"
              href: pages/03-git-github/03-github-portfolio/02-images.qmd
            - text: "STEP 3: Custom content"
              href: pages/03-git-github/03-github-portfolio/03-html.qmd
            - text: "STEP 4: Spruce up your site"
              href: pages/03-git-github/03-github-portfolio/04-jekyll.qmd
            - text: "STEP 5: Add a map"
              href: pages/03-git-github/03-github-portfolio/05-map.qmd
        - section: "UNIT 2: Climate Change"
          contents: 
            - pages/00-course-overviews/stars/02-climate-change/00-home.qmd
        - section: "UNIT 3: Flooding"
          contents: 
            - pages/00-course-overviews/stars/03-flooding/00-home.qmd
        - section: "UNIT 4: Species Distribution"
          contents: 
            - pages/00-course-overviews/stars/04-species-distribution/00-home.qmd
        - section: "UNIT 5: Air Quality"
          contents: 
            - pages/00-course-overviews/stars/05-air-quality/00-home.qmd