project:
  output-dir: _notebooks
  render:
    # - pages/03-git-github/03-github-portfolio/05-map.qmd
    # - notebooks/05-vegetation/vegetation.qmd
    - notebooks/01-climate/climate-*.qmd

execute:
  eval: false
  output: false

format: 
  ipynb: default