project:
  output-dir: _site/stars
  render:
    - pages/00-course-overviews/stars/00-home.qmd
    - pages/00-course-overviews/stars/01-portfolio/
    - pages/01-reproducible-science-tools/open-reproducible-science/
    - pages/03-git-github/03-github-portfolio/
    - notebooks/01-get-started/get-started.qmd
    - notebooks/03-species-distribution/species-distribution.qmd
    - "!index.qmd"

website:
  page-navigation: true
  comments:
    giscus: 
      repo: cu-esiil-edu/stars-2024
  navbar:
    logo-href: "/../index.html"
    left:
      - text: ESIIL Stars Home
        href: pages/00-course-overviews/stars/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true
      logo: img/ESIIL_Stars_logo.png
      collapse-level: 1

      contents:
        - section: "UNIT 1: Build Your Online Portfolio"
          contents:
            - pages/03-git-github/03-github-portfolio/00-introduction.qmd
            - text: "STEP 1: Publish a website"
              href: pages/03-git-github/03-github-portfolio/01-create-portfolio-website.qmd
            - text: "STEP 2: Add images"
              href: pages/03-git-github/03-github-portfolio/02-images.qmd
            - text: "STEP 3: Custom content"
              href: pages/03-git-github/03-github-portfolio/03-html.qmd
            - text: "STEP 4: Spruce up your site"
              href: pages/03-git-github/03-github-portfolio/04-jekyll.qmd
            - text: "STEP 5: Add a map"
              href: pages/03-git-github/03-github-portfolio/05-map.qmd
        - section: "UNIT 2: Climate Change"
          contents: 
            - pages/00-course-overviews/stars/02-climate-change/00-home.qmd
            - section: "Open Science Tools"
              contents:
                - pages/01-reproducible-science-tools/open-reproducible-science/01-intro.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/02-open-science-tools.qmd
                - pages/01-reproducible-science-tools/open-reproducible-science/03-best-practices.qmd
            - section: "Climate Coding Challenge"
              contents:
                - notebooks/01-get-started/get-started.qmd
        - section: "UNIT 3: Species Distribution"
          contents: 
            - pages/00-course-overviews/stars/04-species-distribution/00-home.qmd
            - notebooks/03-species-distribution/species-distribution.qmd
        - section: "UNIT 4: Vegetation Disturbance"
          contents: 
            - pages/00-course-overviews/stars/05-vegetation/00-home.qmd

# Variables
# 01b Climate API
params:
  01-get-started:
    location: "Rapid City, SD"
    station_id: "USC00396947"
    start_date: "1949-10-01"
    end_date: "2023-09-30"
    output_filename: "get-started-stars-data.zip"