project:
  output-dir: _site/css
  render:
    - pages/00-course-overviews/css/home.qmd
    - notebooks/09-urban-heat-island/*.qmd
    - "!index.qmd"

website:
  page-navigation: true
  navbar:
    logo-href: "/../index.html"
    left:
      - text: Indigenous Data Science Workshop with Chicago Symposium
        href: pages/00-course-overviews/css/00-home.qmd

  sidebar:
    - style: docked
      border: false
      search: true

      contents:
        - text: Chicago Symposium
          href: https://chicagosymposium.org/
        - text: Workshop Overview
          href: pages/00-course-overviews/css/00-home.qmd
        - text: Keynote
          href: 
        - section: Session 1
          contents:
            - text: Urban Heat Island
              href: notebooks/0-urban-heat-island/urban-heat-island.qmd
            - text: Try it on GitHub!
              href: https://classroom.github.com/a/UWz9FQ_E