project:
  output-dir: _data
  render:
    # - pages/03-git-github/03-github-portfolio/05-map.qmd
    # - notebooks/05-vegetation/vegetation.qmd
    - notebooks/01-get-started/9*.qmd

execute:
  output: false
  cache: false

filters: 
  - fontawesome

format: 
  ipynb: default