project:
  type: website
  pre-render:
    - scripts/restore_original_files.py
    - scripts/configure_code_cells.py
  render:
    - index.qmd
  post-render:
    - scripts/restore_original_files.py
    #- scripts/update_stored_variable_database.py

bibliography: site_sources.bib

filters:
  - pyodide
  - esiil-callout

website:
  navbar:
    search: true
    logo: img/ESIIL_portal.png
    logo-alt: "ESIIL Environmental Data Analytics Learning Portal"
    logo-href: "index.html"
    right:
      - href: "http://earthdatascience.org"
        text: "Classic earthdatascience.org"
  bread-crumbs: true
  page-footer:
    border: false
    left: 
      - text: "About"
      - text: "ESIIL"
        href: https://esiil.org/
      - text: "Earth Lab"
        href: https://earthlab.colorado.edu/
        
        
format:
  html:
    theme: [flatly, theme-esiil-light.scss]
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?!((http:|https:)\/\/))'
    template-partials:
      - partials/title-block.html
    
code-annotations: "below"

code-block-templates:
  student: 
    echo: true
    eval: false
    class: "student-code"
    highlight: true
  answer: 
    echo: true
    eval: true
    code-fold: true
    code-summary: "See our solution!"
    class: "answer-code"
    highlight: true
  test: 
    echo: true
    eval: true
    class: "test-code"
    highlight: true