name: learning-portal
channels:
  - conda-forge
  - r
  - defaults

dependencies:
  # Python
  # ------
  - python=3.10
  - pip
  # Core
  - numpy
  - xarray
  - pandas
  - dask
  - earthpy
  # API
  - pystac-client
  - earthaccess
  - adlfs
  # Plotting
  - seaborn
  - hvplot
  - geoviews
  - jupyter_bokeh
  - folium
  - selenium
  # Spatial
  - pyproj>=3.0
  - geopandas
  - pyogrio
  - osmnx
  - rioxarray>=0.3.0
  # IO
  - h5netcdf
  # QA
  - flake8
  - flake8-import-order
  - black
  # pip
  - pip:
    - pygbif

  # R
  # -
  - r-base
  - r-essentials
  - r-irkernel
  - r-devtools
  - r-languageserver
  - r-jpeg
  - r-purrr
  - r-magick
  - r-lubridate
  - r-ggplot2
  - r-pals
  - r-maps
  - r-plotly

  # Website build
  - quarto
  - jupyter
  - yaml
  - nbformat
  - nbclient
  - jupyter-cache
  # GitHub CLI
  - gh

