name: learning-portal
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # GitHub CLI
  - gh
  
  # Core
  - numpy
  - xarray
  - pandas
  
  # Plotting
  - seaborn
  - hvplot
  - geoviews
  - folium

  # Spatial
  - pyproj>=3.0
  - geopandas
  - osmnx
  - rioxarray>=0.3.0

  # QA
  - flake8
  - flake8-import-order
  - black
  
  # Website build
  - quarto
  - jupyter
  - nbformat
  - nbclient
