name: learning-portal
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # GitHub CLI
  - gh
  
  # Core
  - numpy
  - xarray
  - pandas
  - dask
  - earthpy

  # API Access
  - pystac-client
  - earthaccess
  - adlfs
  
  # Plotting
  - seaborn
  - hvplot
  - geoviews
  - jupyter_bokeh
  - folium

  # Spatial
  - pyproj>=3.0
  - geopandas
  - pyogrio
  - osmnx
  - rioxarray>=0.3.0

  # QA
  - flake8
  - flake8-import-order
  - black
  
  # Website build
  - quarto
  - jupyter
  - nbformat
  - nbclient
  - jupyter-cache

  # pip
  - pip:
    - pygbif