on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    strategy:
      matrix:
        profile: 
          - mefa
          #- hyrsense
          #- shortcourse
          #- stars
    runs-on: ubuntu-latest
    env:
      QUARTO_PYTHON: /usr/share/miniconda/envs/learning-portal/bin/python
      R_HOME: /usr/share/miniconda/envs/learning-portal/lib/R
      R_LIBS_USER: /usr/share/miniconda/envs/learning-portal/lib/R/library
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      APPEEARS_TASKID: ${{ secrets.APPEEARS_TASKID }}
      GBIF_USER: ${{ secrets.GBIF_USER}}
      GBIF_PWD: ${{ secrets.GBIF_PWD}}
      GBIF_EMAIL: ${{ secrets.GBIF_EMAIL}}
      GBIF_DOWNLOAD_KEY: ${{ secrets.GBIF_DOWNLOAD_KEY }}
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Create and Activate Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: learning-portal
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install earthpy-dev
        run: pip install git+https://github.com/earthlab/earthpy@apppears
        
      - name: Render Main Page
        env: 
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render Profile
        env: 
          QUARTO_PROFILE: ${{ profile }}
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          keep_files: true
