on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

name: Quarto Publish

jobs:
  setup-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
    outputs:
      cache-hit: ${{ steps.cache-conda.outputs.cache-hit }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up cache
        id: cache-conda
        uses: actions/cache@v4
        with:
          path: ~/.conda/envs/learning-portal
          key: conda-${{ hashFiles('environment.yml') }}

      - name: Install conda environment
        if: steps.cache-conda.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: learning-portal
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install earthpy-dev
        if: steps.cache-conda.outputs.cache-hit != 'true'
        run: pip install git+https://github.com/earthlab/earthpy@apppears

      - name: Save conda environment
        if: steps.cache-conda.outputs.cache-hit != 'true'
        run: |
          conda list --export > environment.txt
          
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: 
          - mefa
          #- hyrsense
          #- shortcourse
          #- stars
    env:
      QUARTO_PYTHON: /usr/share/miniconda/envs/learning-portal/bin/python
      R_HOME: /usr/share/miniconda/envs/learning-portal/lib/R
      R_LIBS_USER: /usr/share/miniconda/envs/learning-portal/lib/R/library
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      APPEEARS_TASKID: ${{ secrets.APPEEARS_TASKID }}
      GBIF_USER: ${{ secrets.GBIF_USER}}
      GBIF_PWD: ${{ secrets.GBIF_PWD}}
      GBIF_EMAIL: ${{ secrets.GBIF_EMAIL}}
      GBIF_DOWNLOAD_KEY: ${{ secrets.GBIF_DOWNLOAD_KEY }}
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs/learning-portal
          key: conda-${{ hashFiles('environment.yml') }}
      
      - name: Activate conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: learning-portal
          auto-activate-base: false
          
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render Main Page
        env: 
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render Profile
        env: 
          QUARTO_PROFILE: ${{ matrix.profile }}
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          keep_files: true
