on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: build
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Create and Activate Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: learning-portal
          environment-file: environment.yml
          auto-activate-base: false

      - name: Render Main Page
        uses: quarto-dev/quarto-actions/render@v2
        
      - name: Render Short Course
        env: 
          QUARTO_PROFILE: shortcourse
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render Stars
        env: 
          QUARTO_PROFILE: stars
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render notebooks
        env: 
          QUARTO_PROFILE: nb
          QUARTO_PYTHON: "/usr/share/miniconda/envs/learning-portal/bin/python"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
